### PR TITLE
APB-7316 Fix bug where CBC records were not random

### PR DESCRIPTION
**Pull request by dg-21-hmrc**

### CODE REVIEW

**Review by geoffreywatson — APPROVED** [review]

**Comment by dg-21-hmrc** [comment]
rebuild

**Comment by dg-21-hmrc** [comment]
rebuild

**Comment by dg-21-hmrc** [comment]
rebuild

**Comment by dg-21-hmrc** [comment]
rebuild

**Comment by dg-21-hmrc** [comment]
rebuild

**Comment by dg-21-hmrc** [comment]
rebuild

**Pull request merged**
